function openProductModal(pid=""){let p=db.products.find(x=>x.id===pid)||{id:"",name:"",pack:"",base_price:"",image_data:""};modal.innerHTML=`<div class="modal"><div class="modalbox"><div class="between"><h3>${pid?"Edit":"Add"} Product</h3><button class="btn ghost" onclick="closeModal()">Close</button></div><label>Product Name</label><input id="pn" value="${esc(p.name)}"><label>Pack Size / Unit</label><input id="pp" value="${esc(p.pack||"")}"><label>Normal Price</label><input id="pm" type="number" step="0.01" value="${p.base_price}"><label>Optional Product Image</label><input id="pi" type="file" accept="image/*">${p.image_data?`<div style="margin-top:8px"><img class="product-img" src="${p.image_data}"></div>`:""}<button class="btn primary block" style="margin-top:12px" onclick="saveProduct('${pid}')">Save Product</button></div></div>`}
function closeModal(){modal.innerHTML=""}
async function fileToSmallDataUrl(file){if(!file)return "";let data=await new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});let img=await new Promise((res,rej)=>{let i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=data});let max=420,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);return c.toDataURL("image/jpeg",.70)}
async function saveProduct(pid){try{let image=pi.files[0]?await fileToSmallDataUrl(pi.files[0]):"";await rpc("app_admin_product",{p_token:token(),p_action:"save",p_payload:{id:pid,name:pn.value.trim(),pack:pp.value.trim(),base_price:Number(pm.value),image_data:image,active:true}});closeModal();await refreshState(false);renderAdmin("products")}catch(e){alert(e.message)}}
async function deleteProduct(pid){if(!confirm("Delete this product? Old order item history remains."))return;try{await rpc("app_admin_product",{p_token:token(),p_action:"delete",p_payload:{id:pid}});await refreshState(false);renderAdmin("products")}catch(e){alert(e.message)}}
function openPriceModal(pid){let p=db.products.find(x=>x.id===pid);modal.innerHTML=`<div class="modal"><div class="modalbox"><div class="between"><div><h3>${esc(p.name)} – Customer Prices</h3><div class="small muted">Normal: ${money(p.base_price)}. Blank = normal price.</div></div><button class="btn ghost" onclick="closeModal()">Close</button></div>${db.customers.map(c=>{let x=db.prices.find(z=>z.product_id===pid&&z.customer_id===c.id);return `<div class="item"><div class="between"><div><b>${esc(c.shop_name)}</b><div class="small muted">${esc(c.mobile)}</div></div><div style="width:130px"><input id="sp_${c.id}" type="number" step="0.01" placeholder="${p.base_price}" value="${x?.price??""}"></div></div></div>`}).join("")||"<p>No customers yet.</p>"}<button class="btn primary block" onclick="saveSpecialPrices('${pid}')">Save Customer Prices</button></div></div>`}
async function saveSpecialPrices(pid){try{for(const c of db.customers){let e=document.getElementById("sp_"+c.id);await rpc("app_admin_price",{p_token:token(),p_customer_id:c.id,p_product_id:pid,p_price:e.value===""?null:Number(e.value)})}closeModal();await refreshState(false);renderAdmin("products")}catch(e){alert(e.message)}}

function adminCustomers(){
 return `<div class="card"><div class="between"><h3>Customers</h3><button class="btn primary" onclick="openCustomerModal()">+ Add</button></div><div class="list">${db.customers.map(c=>`<div class="item"><div class="between"><div><b>${esc(c.shop_name)}</b><div class="small muted">${esc(c.mobile)} • ${esc(c.owner_name||"")}</div><div class="small">${esc(c.address||"")}</div></div><div><div class="price">${money(customerBalance(c.id))}</div><div class="small muted">balance</div></div></div><div class="row" style="margin-top:8px"><button class="btn ghost" onclick="openCustomerModal('${c.id}')">Edit</button><button class="btn purple" onclick="exportCustomer('${c.id}')">Customer Excel</button></div></div>`).join("")||"<p>No customers yet.</p>"}</div></div>`;
}
function openCustomerModal(cid=""){let c=db.customers.find(x=>x.id===cid)||{id:"",shop_name:"",owner_name:"",mobile:"",address:"",active:true};modal.innerHTML=`<div class="modal"><div class="modalbox"><div class="between"><h3>${cid?"Edit":"Add"} Customer</h3><button class="btn ghost" onclick="closeModal()">Close</button></div><label>Shop Name</label><input id="cs" value="${esc(c.shop_name)}"><label>Owner</label><input id="co" value="${esc(c.owner_name||"")}"><label>Mobile</label><input id="cmob" maxlength="10" value="${esc(c.mobile)}"><label>Address / Landmark</label><input id="ca" value="${esc(c.address||"")}"><label>${cid?"New PIN (leave blank to keep current)":"4-digit PIN"}</label><input id="cpin" type="password" maxlength="4"><label>Active</label><select id="cactive"><option value="true" ${c.active!==false?"selected":""}>Active</option><option value="false" ${c.active===false?"selected":""}>Inactive</option></select><button class="btn primary block" style="margin-top:12px" onclick="saveCustomer('${cid}')">Save Customer</button></div></div>`}
async function saveCustomer(cid){try{await rpc("app_admin_customer",{p_token:token(),p_payload:{id:cid,shop_name:cs.value.trim(),owner_name:co.value.trim(),mobile:cmob.value.trim(),address:ca.value.trim(),pin:cpin.value.trim(),active:cactive.value==="true"}});closeModal();await refreshState(false);renderAdmin("customers")}catch(e){alert(e.message)}}
