function adminPaymentHistory(){
 return `<div class="card"><div class="between"><h3>Payment History</h3><button class="btn ghost" onclick="exportPayments()">Export Payments Excel</button></div><div style="overflow:auto"><table><thead><tr><th>Date/Time</th><th>Shop</th><th>Order</th><th>Amount</th><th>Method</th><th>Status / Action</th><th>Reference</th></tr></thead><tbody>${db.payments.map(p=>{let c=customerById(p.customer_id);return `<tr><td>${new Date(p.created_at).toLocaleString()}</td><td>${esc(c?.shop_name||"")}</td><td>${esc(p.order_id||"")}</td><td>${money(p.amount)}</td><td>${esc(p.method||"")}</td><td>${p.status==="pending"?`<div class="row"><button class="btn green" onclick="reviewPayment('${p.id}','success')">Received</button><button class="btn red" onclick="reviewPayment('${p.id}','rejected')">Reject</button></div>`:`<span class="pill">${esc(p.status)}</span>`}</td><td>${esc(p.reference||"")}</td></tr>`}).join("")||`<tr><td colspan="7">No payments.</td></tr>`}</tbody></table></div></div>`;
}
async function reviewPayment(pid,status){try{await rpc("app_admin_payment_review",{p_token:token(),p_payment_id:pid,p_status:status});await refreshState(false);renderAdmin("payments")}catch(e){alert(e.message)}}

function adminReports(){return `<div class="card"><h3>Excel Reports</h3><p class="muted">Exports contain order date/time, shop, product, quantity, unit price, totals, balances and payment details.</p><div class="grid"><button class="btn primary" onclick="exportOrders()">Download Orders Excel</button><button class="btn green" onclick="exportPayments()">Download Payments Excel</button></div><hr style="border:0;border-top:1px solid var(--line);margin:16px 0"><h3>Customer-specific Excel</h3><select id="reportCustomer"><option value="">Choose customer</option>${db.customers.map(c=>`<option value="${c.id}">${esc(c.shop_name)} - ${esc(c.mobile)}</option>`).join("")}</select><button class="btn purple block" style="margin-top:10px" onclick="if(reportCustomer.value)exportCustomer(reportCustomer.value)">Download Customer Statement</button></div>`}
function adminSettings(){return `<div class="card"><h3>Agency Settings</h3><label>Agency Heading</label><input id="agency" value="${esc(s().agency_name||"")}"><label>WhatsApp Alert Number</label><input id="wa" value="${esc(s().whatsapp||"")}"><label>UPI ID</label><input id="upi" value="${esc(s().upi_id||"")}"><label>Order / Delivery Contact</label><input id="contact" value="${esc(s().contact||"")}"><label>Credit Days</label><input id="credit" type="number" value="${s().credit_days||3}"><button class="btn primary block" style="margin-top:12px" onclick="saveSettings()">Save Settings</button></div>`}
async function saveSettings(){try{await rpc("app_admin_settings",{p_token:token(),p_agency_name:agency.value.trim(),p_whatsapp:wa.value.trim(),p_upi_id:upi.value.trim(),p_contact:contact.value.trim(),p_credit_days:Number(credit.value||3)});await refreshState(false);renderAdmin("settings")}catch(e){alert(e.message)}}

function customerTabs(active){return `<div class="tabs">${[["home","Home"],["order","Order Tomorrow"],["orders","My Orders"],["payments","Payment History"],["account","Account"]].map(([k,t])=>`<button class="tab ${active===k?"active":""}" onclick="renderCustomer('${k}')">${t}</button>`).join("")}</div>`}
function renderCustomer(page){currentPage=page;let c=db.customers[0];if(!c){clearSession();return customerLogin()}let body=customerTabs(page);if(page==="home")body+=customerHome(c);if(page==="order")body+=customerOrder(c);if(page==="orders")body+=customerOrders(c);if(page==="payments")body+=customerPaymentHistory(c);if(page==="account")body+=customerAccount(c);app.innerHTML=shell(body,"customer")}
function customerHome(c){return `<div class="grid"><div class="card"><div class="muted">Current Outstanding</div><div class="stat">${money(customerBalance(c.id))}</div></div><div class="card"><div class="muted">Tomorrow</div><div class="stat">${db.orders.some(o=>o.delivery_date===tomorrow()&&o.status!=="cancelled")?"Ordered":"Not ordered"}</div></div></div><br><div class="grid"><button class="btn primary" onclick="renderCustomer('order')">Place Tomorrow Order</button><button class="btn green" onclick="renderCustomer('orders')">Orders & Payment</button><button class="btn ghost" onclick="location.href='tel:${esc(s().contact||"")}'">Call Agency</button></div>`}
function customerOrder(c){
 return `<div class="card"><div class="between"><h3>Order for Tomorrow</h3><span class="pill">${tomorrow()}</span></div><div class="list">${db.products.filter(p=>p.active).map(p=>{let pr=priceFor(p.id,c.id);return `<div class="item product-line">${p.image_data?`<img class="product-img" src="${p.image_data}">`:`<div class="product-img" style="display:grid;place-items:center">Milk</div>`}<div><b>${esc(p.name)}</b><div class="small muted">${esc(p.pack||"")}</div><div class="price">${money(pr)}</div>${pr!==Number(p.base_price)?`<div class="small" style="color:var(--green)">Special price for your shop</div>`:""}</div><div class="qty"><button onclick="chg('${p.id}',-1)">−</button><input id="q_${p.id}" type="number" min="0" value="0" oninput="calcTotal()"><button onclick="chg('${p.id}',1)">+</button></div></div>`}).join("")}</div><div class="between" style="margin-top:12px"><b>Total</b><div class="stat" id="ototal">₹0</div></div><button class="btn primary block" style="margin-top:12px" onclick="placeOrder()">PLACE ORDER</button></div>`;
}
function chg(pid,d){let e=document.getElementById("q_"+pid);e.value=Math.max(0,Number(e.value||0)+d);calcTotal()}
function calcTotal(){let c=db.customers[0],t=0;db.products.filter(p=>p.active).forEach(p=>{let e=document.getElementById("q_"+p.id);if(e)t+=Number(e.value||0)*priceFor(p.id,c.id)});if(document.getElementById("ototal"))ototal.textContent=money(t)}
